Proceso POSICION
	Escribir "INGRESE LA VELOCIDAD DEL AUTO DE ATRAS(KM/H)"
	Leer V1
	Escribir "INGRESE LA VELOCIDAD DEL OTRO AUTO(KM/H) "
	Leer V2
	Escribir "INGRESE LA DISTANCIA QUE LOS SEPARA(KM)"
	Leer D
	T<-D/(V1-V2)
	M<-(T*60)
	Escribir "EL TIEMPO QUE SE DEMORA EL AUTO DE ATRAS EN ALCANZAR AL OTRO AUTO ES:" , M, "MIN"
	
FinProceso
